/**
 * Voice events — Phase 7 Day 52.
 *
 * The Wyrm's Voice (or other synchronized world events) fire at
 * scheduled chapter transitions. Distinct from per-turn wonder
 * events: a Voice fires globally — every player active in that
 * chapter window sees the same line in their narration. Mechanic:
 * a high-salience world_lore entry tagged 'voice', plus a one-line
 * memory inject for any session whose turn 1 falls inside the
 * window.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface VoiceEvent {
  id: string;
  chapterId: number;
  /** Templated line the narrator weaves in. NOT generated by an
   *  LLM — deterministic flavor for cost discipline. */
  line: string;
  /** Days the voice fragment stays live after firing. After this,
   *  it stops surfacing in turn-1 memory injection. */
  durationDays: number;
}

const cache = new Map<number, VoiceEvent[] | null>();

export function loadVoicesForChapter(chapterId: number): VoiceEvent[] {
  if (cache.has(chapterId)) return cache.get(chapterId) ?? [];
  const path = join(
    process.cwd(),
    "content",
    "story",
    "voices",
    `${chapterId}.json`,
  );
  if (!existsSync(path)) {
    cache.set(chapterId, null);
    return [];
  }
  try {
    const raw = JSON.parse(readFileSync(path, "utf-8")) as {
      voices?: VoiceEvent[];
    };
    const voices = Array.isArray(raw.voices) ? raw.voices : [];
    cache.set(chapterId, voices);
    return voices;
  } catch {
    cache.set(chapterId, null);
    return [];
  }
}

export function clearVoiceCache(): void {
  cache.clear();
}
